"""
export_binary_weights.py — Convert model_weights.json to compact binary file
Runs on: Laptop

Converts float32 weights to a single binary file that MicroPython can load
using struct.unpack() — much faster and smaller than parsing Python lists.

Format:
    4 bytes: number of weight arrays (uint32)
    For each array:
        4 bytes: number of elements (uint32)
        N*4 bytes: float32 values (little-endian)
    Order: W1, b1, W2, b2, W3, b3, W4, b4 (all flattened)
"""

import json
import struct
import os
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
JSON_PATH = os.path.join(SCRIPT_DIR, "model_weights.json")
BIN_PATH = os.path.join(SCRIPT_DIR, "model_weights.bin")
LOADER_PATH = os.path.join(SCRIPT_DIR, "model_data.py")

print("[INFO] Loading weights from JSON...")
with open(JSON_PATH, 'r') as f:
    weights = json.load(f)

classes = weights['classes']
img_size = weights['img_size']
print(f"  Classes: {classes}")
print(f"  Image size: {img_size}")

# Flatten all weight arrays and write as binary
weight_names = ['W1', 'b1', 'W2', 'b2', 'W3', 'b3', 'W4', 'b4']
arrays = []
shapes = []

for name in weight_names:
    arr = np.array(weights[name], dtype=np.float32).flatten()
    arrays.append(arr)
    shapes.append(weights[name])
    print(f"  {name}: {len(arr)} values")

# Write binary file
with open(BIN_PATH, 'wb') as f:
    # Header: number of arrays
    f.write(struct.pack('<I', len(arrays)))
    # Each array: count + data
    for arr in arrays:
        f.write(struct.pack('<I', len(arr)))
        f.write(arr.tobytes())  # float32 little-endian

bin_size = os.path.getsize(BIN_PATH)
print(f"\n[OK] Binary weights saved: {BIN_PATH}")
print(f"     Size: {bin_size} bytes ({bin_size/1024:.1f} KB)")

# Now create a minimal model_data.py that loads from binary
# This replaces the huge text-based model_data.py

# We need to store the shapes so the loader can reshape
w1_shape = list(np.array(weights['W1']).shape)
w2_shape = list(np.array(weights['W2']).shape)
w3_shape = list(np.array(weights['W3']).shape)
w4_shape = list(np.array(weights['W4']).shape)

loader_code = f'''"""
model_data.py — CNN weights loader for ESP32
Auto-generated by export_binary_weights.py
Loads weights from model_weights.bin (compact binary format)
"""

import struct
import gc

CLASSES = {classes}
IMG_SIZE = {img_size}

def _load_floats(f, count):
    """Read count float32 values from binary file."""
    data = f.read(count * 4)
    vals = list(struct.unpack('<' + 'f' * count, data))
    return vals

def _reshape_4d(flat, shape):
    """Reshape flat list to 4D nested list [d0][d1][d2][d3]."""
    d0, d1, d2, d3 = shape
    result = []
    idx = 0
    for i in range(d0):
        l1 = []
        for j in range(d1):
            l2 = []
            for k in range(d2):
                l3 = []
                for l in range(d3):
                    l3.append(flat[idx])
                    idx += 1
                l2.append(l3)
            l1.append(l2)
        result.append(l1)
    return result

def _reshape_2d(flat, shape):
    """Reshape flat list to 2D nested list [d0][d1]."""
    d0, d1 = shape
    result = []
    idx = 0
    for i in range(d0):
        row = []
        for j in range(d1):
            row.append(flat[idx])
            idx += 1
        result.append(row)
    return result

print("[INFO] Loading model weights from binary...")
gc.collect()
mem_before = gc.mem_free()

f = open("model_weights.bin", "rb")

# Read header
n_arrays = struct.unpack('<I', f.read(4))[0]

# Read W1: {w1_shape}
n = struct.unpack('<I', f.read(4))[0]
W1 = _reshape_4d(_load_floats(f, n), {w1_shape})
gc.collect()
print("  W1 loaded")

# Read b1
n = struct.unpack('<I', f.read(4))[0]
b1 = _load_floats(f, n)
print("  b1 loaded")

# Read W2: {w2_shape}
n = struct.unpack('<I', f.read(4))[0]
W2 = _reshape_4d(_load_floats(f, n), {w2_shape})
gc.collect()
print("  W2 loaded")

# Read b2
n = struct.unpack('<I', f.read(4))[0]
b2 = _load_floats(f, n)
print("  b2 loaded")

# Read W3: {w3_shape}
n = struct.unpack('<I', f.read(4))[0]
W3 = _reshape_2d(_load_floats(f, n), {w3_shape})
gc.collect()
print("  W3 loaded")

# Read b3
n = struct.unpack('<I', f.read(4))[0]
b3 = _load_floats(f, n)
print("  b3 loaded")

# Read W4: {w4_shape}
n = struct.unpack('<I', f.read(4))[0]
W4 = _reshape_2d(_load_floats(f, n), {w4_shape})
gc.collect()
print("  W4 loaded")

# Read b4
n = struct.unpack('<I', f.read(4))[0]
b4 = _load_floats(f, n)
print("  b4 loaded")

f.close()
gc.collect()

mem_after = gc.mem_free()
print(f"[OK]   Model loaded. Memory used: {{mem_before - mem_after}} bytes")
print(f"[INFO] Free memory: {{mem_after}} bytes")
'''

with open(LOADER_PATH, 'w') as f:
    f.write(loader_code)

print(f"[OK] Loader saved: {LOADER_PATH}")
print(f"     Size: {os.path.getsize(LOADER_PATH)} bytes")
print(f"\nUpload these 2 files to ESP via Thonny:")
print(f"  1. model_weights.bin ({bin_size/1024:.1f} KB)")
print(f"  2. model_data.py ({os.path.getsize(LOADER_PATH)/1024:.1f} KB)")
