"""
final_submission.py — Phase 6: Real-time RPS Classification on ESP32S3
Runs on: ESP32S3 (XIAO ESP32S3 Sense)

Purpose:
    Capture a 96x96 grayscale BMP image from the camera,
    resize to 32x32, apply threshold preprocessing,
    run CNN forward pass using trained weights,
    and print the classification result over serial.
    Runs in a continuous loop for near real-time classification.

Adapted from provided working examples:
    - Camera init/capture: camera_test.py (pin config, init, set_bmp_out)
    - Image preprocessing: image_preprocessing.py
      (resize_96x96_to_32x32_and_threshold function)
    - WiFi: Wifi.py Sta class (Sharil Tumin, MIT License) — optional

Changes from originals:
    - Combined camera + preprocessing + CNN inference into one script
    - CNN forward pass implemented in pure MicroPython (no numpy)
    - Weights loaded from model_data.py (auto-generated by train_cnn.py)

CNN Architecture (must match train_cnn.py):
    Input:    32x32x1 (grayscale, 0.0 or 1.0 after threshold)
    Conv2D:   8 filters, 3x3, ReLU      → 30x30x8
    MaxPool:  2x2                        → 15x15x8
    Conv2D:   16 filters, 3x3, ReLU     → 13x13x16
    MaxPool:  2x2                        → 6x6x16
    Flatten:  576
    Dense:    32, ReLU
    Dense:    3, softmax (rock/paper/scissors)

Original CNN inference code by project team.
"""

import gc
from time import sleep, ticks_ms, ticks_diff

# ─── Step 1: Load trained model weights ───
# model_data.py is auto-generated by train_cnn.py on the laptop
# It must be uploaded to the ESP filesystem via Thonny
print("[INFO] Loading model weights...")
gc.collect()
mem_before = gc.mem_free()

try:
    import model_data
    CLASSES = model_data.CLASSES
    IMG_SIZE = model_data.IMG_SIZE
    W1 = model_data.W1
    b1 = model_data.b1
    W2 = model_data.W2
    b2 = model_data.b2
    W3 = model_data.W3
    b3 = model_data.b3
    W4 = model_data.W4
    b4 = model_data.b4
    print(f"[OK]   Model loaded. Classes: {CLASSES}")
    gc.collect()
    mem_after = gc.mem_free()
    print(f"[INFO] Memory used by model: {mem_before - mem_after} bytes")
    print(f"[INFO] Free memory: {mem_after} bytes")
except ImportError:
    print("[FAIL] model_data.py not found!")
    print("[TIP]  Upload model_data.py to ESP via Thonny")
    raise

# ─── Step 2: Initialize camera ───
# Adapted from provided camera_test.py — identical pin config
from camera import Camera, GrabMode, PixelFormat, FrameSize, GainCeiling

CAMERA_PARAMETERS = {
    "data_pins": [15, 17, 18, 16, 14, 12, 11, 48],
    "vsync_pin": 38,
    "href_pin": 47,
    "sda_pin": 40,
    "scl_pin": 39,
    "pclk_pin": 13,
    "xclk_pin": 10,
    "xclk_freq": 20000000,
    "powerdown_pin": -1,
    "reset_pin": -1,
}

print("[INFO] Initializing camera...")
cam = Camera(**CAMERA_PARAMETERS)
cam.init()
cam.set_bmp_out(True)
print("[OK]   Camera ready")

# ─── Step 3: Preprocessing function ───
# The provided image_preprocessing.py assumes 96x96 grayscale BMP,
# but the camera actually outputs 128x128 24-bit RGB BMP (49,206 bytes).
# This function handles the actual camera format.

def preprocess_camera_bmp(bmp_data, threshold=128):
    """Convert 128x128 RGB BMP from camera → 32x32 grayscale thresholded BMP.

    Camera output: 128x128, 24-bit RGB, no palette, pixel data at offset 54
    Target output: 32x32, 8-bit grayscale, with palette, thresholded to 0/255
    """
    # Parse input BMP header
    in_offset = int.from_bytes(bmp_data[10:14], 'little')
    in_w = int.from_bytes(bmp_data[18:22], 'little')
    in_h_raw = int.from_bytes(bmp_data[22:26], 'little')
    in_bpp = int.from_bytes(bmp_data[28:30], 'little')
    # CRITICAL FIX: int.from_bytes returns UNSIGNED in MicroPython.
    # BMP height is a SIGNED 32-bit int (negative = top-down row order).
    # Must manually convert unsigned → signed.
    if in_h_raw >= 0x80000000:
        in_h_raw = in_h_raw - 0x100000000  # e.g., 4294967168 → -128
    in_h = abs(in_h_raw)  # now correctly 128, not 4294967168
    bottom_up = in_h_raw > 0  # now correctly False for top-down
    bytes_per_pixel = in_bpp // 8
    in_row_size = ((in_w * bytes_per_pixel + 3) // 4) * 4

    # Output: 32x32 8-bit grayscale BMP
    NEW_W = 32
    NEW_H = 32
    HEADER = 14
    DIB = 40
    PALETTE = 256 * 4
    OUT_ROW_SIZE = 32
    out_pixel_size = OUT_ROW_SIZE * NEW_H
    out_file_size = HEADER + DIB + PALETTE + out_pixel_size

    out = bytearray(out_file_size)
    out[0:2] = b'BM'
    out[2:6] = out_file_size.to_bytes(4, 'little')
    out[10:14] = (HEADER + DIB + PALETTE).to_bytes(4, 'little')
    out[14:18] = DIB.to_bytes(4, 'little')
    out[18:22] = NEW_W.to_bytes(4, 'little')
    out[22:26] = NEW_H.to_bytes(4, 'little')
    out[26:28] = b'\x01\x00'
    out[28:30] = b'\x08\x00'
    out[34:38] = out_pixel_size.to_bytes(4, 'little')

    palette_start = HEADER + DIB
    for i in range(256):
        idx = palette_start + i * 4
        out[idx] = i; out[idx+1] = i; out[idx+2] = i; out[idx+3] = 0

    out_pixel_start = HEADER + DIB + PALETTE
    scale_x = in_w / NEW_W
    scale_y = in_h / NEW_H

    for new_y in range(NEW_H):
        for new_x in range(NEW_W):
            # Map output pixel to input pixel
            old_x = int(new_x * scale_x)
            old_y = int(new_y * scale_y)

            # Handle row order:
            # If bottom_up (positive height): row 0 = bottom of image
            #   output row 0 (bottom) maps to input row 0 (bottom)
            # If top_down (negative height): row 0 = top of image
            #   output row 0 (bottom) maps to input row (in_h-1-0) = last row
            if bottom_up:
                src_row = old_y
            else:
                # Top-down input → bottom-up output: flip the row
                src_row = (in_h - 1 - old_y)

            src_offset = in_offset + src_row * in_row_size + old_x * bytes_per_pixel

            # Bounds check
            if src_offset + bytes_per_pixel > len(bmp_data):
                pixel = 255
            elif bytes_per_pixel >= 3:
                # IMPORTANT: cam.capture() returns a memoryview with SIGNED bytes
                # (-128 to 127). We must convert to unsigned (0-255) with & 0xFF.
                b_val = bmp_data[src_offset] & 0xFF
                g_val = bmp_data[src_offset + 1] & 0xFF
                r_val = bmp_data[src_offset + 2] & 0xFF
                gray = (r_val + g_val + b_val) // 3
                pixel = 255 if gray >= threshold else 0
            else:
                gray = bmp_data[src_offset] & 0xFF
                pixel = 255 if gray >= threshold else 0

            out[out_pixel_start + new_y * OUT_ROW_SIZE + new_x] = pixel

    return out

# ─── Step 4: CNN Forward Pass Functions ───
# These implement the same math as train_cnn.py but in pure MicroPython
# (no numpy available on ESP)

def conv2d(pixels, W, b, in_h, in_w, in_c, n_filters, fh, fw):
    """2D convolution. All data as flat lists for memory efficiency.
    pixels: flat list [in_h * in_w * in_c]
    W: nested list [fh][fw][in_c][n_filters]
    b: list [n_filters]
    Returns: flat list [out_h * out_w * n_filters]
    """
    out_h = in_h - fh + 1
    out_w = in_w - fw + 1
    out = [0.0] * (out_h * out_w * n_filters)

    for f in range(n_filters):
        for i in range(out_h):
            for j in range(out_w):
                val = b[f]
                for fi in range(fh):
                    for fj in range(fw):
                        for c in range(in_c):
                            px_idx = ((i + fi) * in_w + (j + fj)) * in_c + c
                            val += pixels[px_idx] * W[fi][fj][c][f]
                out_idx = (i * out_w + j) * n_filters + f
                # ReLU inline (fused with conv for speed)
                out[out_idx] = val if val > 0 else 0.0

    return out, out_h, out_w


def maxpool2d(pixels, in_h, in_w, n_c):
    """2x2 max pooling. Input/output as flat lists.
    Returns: flat list [out_h * out_w * n_c]
    """
    out_h = in_h // 2
    out_w = in_w // 2
    out = [0.0] * (out_h * out_w * n_c)

    for i in range(out_h):
        for j in range(out_w):
            for c in range(n_c):
                max_val = -999999.0
                for di in range(2):
                    for dj in range(2):
                        idx = ((i * 2 + di) * in_w + (j * 2 + dj)) * n_c + c
                        if pixels[idx] > max_val:
                            max_val = pixels[idx]
                out_idx = (i * out_w + j) * n_c + c
                out[out_idx] = max_val

    return out, out_h, out_w


def dense(inputs, W, b, n_in, n_out, apply_relu=True):
    """Dense (fully connected) layer.
    inputs: list [n_in]
    W: nested list [n_in][n_out]
    b: list [n_out]
    Returns: list [n_out]
    """
    out = [0.0] * n_out
    for j in range(n_out):
        val = b[j]
        for i in range(n_in):
            val += inputs[i] * W[i][j]
        if apply_relu:
            out[j] = val if val > 0 else 0.0
        else:
            out[j] = val
    return out


def softmax(x):
    """Softmax activation. Returns probabilities that sum to 1."""
    # Find max for numerical stability
    max_val = x[0]
    for v in x:
        if v > max_val:
            max_val = v
    # Compute exp(x - max)
    exp_vals = [0.0] * len(x)
    total = 0.0
    for i in range(len(x)):
        # Clamp to avoid overflow
        val = x[i] - max_val
        if val < -20:
            val = -20
        # Simple exp approximation for MicroPython
        # e^x ≈ (1 + x/256)^256  — good enough for softmax
        ev = 1.0
        v = 1.0 + val / 256.0
        for _ in range(8):
            v = v * v  # squaring 8 times = ^256
        exp_vals[i] = v
        total += v
    # Normalize
    for i in range(len(exp_vals)):
        exp_vals[i] /= total
    return exp_vals


def predict(pixels_32x32):
    """Run full CNN forward pass on a 32x32 grayscale image.
    pixels_32x32: flat list of 1024 float values (0.0 or 1.0)
    Returns: (class_name, confidence, all_probabilities)
    """
    # Input shape: 32x32x1 as flat list
    x = pixels_32x32

    # Conv1: 32x32x1 → 30x30x8 (with ReLU fused)
    x, h, w = conv2d(x, W1, b1, 32, 32, 1, 8, 3, 3)

    # Pool1: 30x30x8 → 15x15x8
    x, h, w = maxpool2d(x, h, w, 8)

    # Conv2: 15x15x8 → 13x13x16 (with ReLU fused)
    x, h, w = conv2d(x, W2, b2, h, w, 8, 16, 3, 3)

    # Pool2: 13x13x16 → 6x6x16
    x, h, w = maxpool2d(x, h, w, 16)

    # Flatten: 6x6x16 = 576
    # x is already flat

    # Dense1: 576 → 32 (with ReLU)
    x = dense(x, W3, b3, 576, 32, apply_relu=True)

    # Dense2: 32 → n_classes
    n_classes = len(CLASSES)
    x = dense(x, W4, b4, 32, n_classes, apply_relu=False)

    # Softmax
    probs = softmax(x)

    # Find best class
    best_idx = 0
    best_prob = probs[0]
    for i in range(1, len(probs)):
        if probs[i] > best_prob:
            best_prob = probs[i]
            best_idx = i

    return CLASSES[best_idx], best_prob, probs


def extract_pixels_from_32x32_bmp(bmp_data, threshold_value=128):
    """Extract pixel values from a 32x32 8-bit BMP and normalize.
    The BMP was already thresholded by image_preprocessing.py,
    so pixels are 0 or 255. We convert to 0.0 or 1.0.

    BMP stores rows bottom-to-top, so we flip vertically to match
    the training data orientation.

    Returns: flat list of 1024 floats
    """
    HEADER_SIZE = 14 + 40 + 256 * 4  # BMP + DIB + palette = 1078
    ROW_SIZE = 32  # 32 pixels, no padding needed (32 % 4 == 0)

    pixels = [0.0] * 1024

    for row in range(32):
        # BMP is bottom-up, flip so row 0 = top of image
        bmp_row = 31 - row
        offset = HEADER_SIZE + bmp_row * ROW_SIZE
        for col in range(32):
            px = bmp_data[offset + col]
            # Normalize: 0 → 0.0, 255 → 1.0
            pixels[row * 32 + col] = px / 255.0

    # Normalize orientation so hand always enters from left
    pixels = normalize_orientation_flat(pixels)
    return pixels


def normalize_orientation_flat(pixels):
    """Rotate 32x32 flat pixel array so hand (black pixels, value < 0.5)
    enters from the top edge. Must match train_cnn.py normalize_orientation()."""
    top = sum(1 for x in range(32) if pixels[x] < 0.5)
    bottom = sum(1 for x in range(32) if pixels[31*32 + x] < 0.5)
    left = sum(1 for y in range(32) if pixels[y*32] < 0.5)
    right = sum(1 for y in range(32) if pixels[y*32 + 31] < 0.5)

    counts = [('left', left), ('right', right), ('top', top), ('bottom', bottom)]
    dominant = max(counts, key=lambda c: c[1])[0]

    if dominant == 'top':
        return pixels
    elif dominant == 'bottom':
        return list(reversed(pixels))
    elif dominant == 'left':
        # 90 CW: left→top. old[y][x] → new[x][31-y]
        out = [0.0] * 1024
        for y in range(32):
            for x in range(32):
                out[x * 32 + (31 - y)] = pixels[y * 32 + x]
        return out
    elif dominant == 'right':
        # 90 CCW: right→top. old[y][x] → new[31-x][y]
        out = [0.0] * 1024
        for y in range(32):
            for x in range(32):
                out[(31 - x) * 32 + y] = pixels[y * 32 + x]
        return out
    return pixels


# ─── Step 5: Main inference loop ───
print("\n" + "=" * 40)
print("  RPS CLASSIFIER — LIVE INFERENCE")
print("=" * 40)
print(f"  Classes: {CLASSES}")
print(f"  Image size: {IMG_SIZE}x{IMG_SIZE}")
print(f"  Hold hand gesture in front of camera")
print(f"  Results print to serial every few seconds")
print("=" * 40 + "\n")

# Fixed threshold to match training data preprocessing
THRESHOLD = 128
print(f"[OK]   Using fixed threshold: {THRESHOLD}")

inference_count = 0

while True:
    try:
        gc.collect()
        t_start = ticks_ms()

        # Capture
        raw_img = cam.capture()

        # Preprocess: resize 128x128 RGB → 32x32 grayscale + threshold
        small_bmp = preprocess_camera_bmp(raw_img, THRESHOLD)
        del raw_img
        gc.collect()

        # Extract normalized pixel array from 32x32 BMP
        pixels = extract_pixels_from_32x32_bmp(small_bmp, THRESHOLD)
        del small_bmp
        gc.collect()

        # Run CNN inference
        class_name, confidence, probs = predict(pixels)
        del pixels
        gc.collect()

        t_end = ticks_ms()
        inference_count += 1
        total_ms = ticks_diff(t_end, t_start)

        # Format output
        prob_str = " | ".join(
            f"{CLASSES[i]}:{probs[i]:.0%}" for i in range(len(CLASSES))
        )

        print(f"[#{inference_count:3d}] {class_name:>8s} ({confidence:.0%})  "
              f"| {prob_str} "
              f"| {total_ms}ms")

        sleep(0.5)

    except KeyboardInterrupt:
        print("\n[STOP] Inference stopped by user")
        break
    except MemoryError:
        print("[ERR]  Out of memory! Resetting...")
        gc.collect()
        sleep(2)
    except Exception as e:
        print(f"[ERR]  {e}")
        gc.collect()
        sleep(2)

print(f"\nTotal inferences: {inference_count}")
print(f"Free memory: {gc.mem_free()} bytes")
