"""
model_data.py — CNN weights loader for ESP32
Auto-generated by export_binary_weights.py
Loads weights from model_weights.bin (compact binary format)
"""

import struct
import gc

CLASSES = ['paper', 'rock', 'scissors']
IMG_SIZE = 32

def _load_floats(f, count):
    """Read count float32 values from binary file."""
    data = f.read(count * 4)
    vals = list(struct.unpack('<' + 'f' * count, data))
    return vals

def _reshape_4d(flat, shape):
    """Reshape flat list to 4D nested list [d0][d1][d2][d3]."""
    d0, d1, d2, d3 = shape
    result = []
    idx = 0
    for i in range(d0):
        l1 = []
        for j in range(d1):
            l2 = []
            for k in range(d2):
                l3 = []
                for l in range(d3):
                    l3.append(flat[idx])
                    idx += 1
                l2.append(l3)
            l1.append(l2)
        result.append(l1)
    return result

def _reshape_2d(flat, shape):
    """Reshape flat list to 2D nested list [d0][d1]."""
    d0, d1 = shape
    result = []
    idx = 0
    for i in range(d0):
        row = []
        for j in range(d1):
            row.append(flat[idx])
            idx += 1
        result.append(row)
    return result

print("[INFO] Loading model weights from binary...")
gc.collect()
mem_before = gc.mem_free()

f = open("model_weights.bin", "rb")

# Read header
n_arrays = struct.unpack('<I', f.read(4))[0]

# Read W1: [3, 3, 1, 8]
n = struct.unpack('<I', f.read(4))[0]
W1 = _reshape_4d(_load_floats(f, n), [3, 3, 1, 8])
gc.collect()
print("  W1 loaded")

# Read b1
n = struct.unpack('<I', f.read(4))[0]
b1 = _load_floats(f, n)
print("  b1 loaded")

# Read W2: [3, 3, 8, 16]
n = struct.unpack('<I', f.read(4))[0]
W2 = _reshape_4d(_load_floats(f, n), [3, 3, 8, 16])
gc.collect()
print("  W2 loaded")

# Read b2
n = struct.unpack('<I', f.read(4))[0]
b2 = _load_floats(f, n)
print("  b2 loaded")

# Read W3: [576, 32]
n = struct.unpack('<I', f.read(4))[0]
W3 = _reshape_2d(_load_floats(f, n), [576, 32])
gc.collect()
print("  W3 loaded")

# Read b3
n = struct.unpack('<I', f.read(4))[0]
b3 = _load_floats(f, n)
print("  b3 loaded")

# Read W4: [32, 3]
n = struct.unpack('<I', f.read(4))[0]
W4 = _reshape_2d(_load_floats(f, n), [32, 3])
gc.collect()
print("  W4 loaded")

# Read b4
n = struct.unpack('<I', f.read(4))[0]
b4 = _load_floats(f, n)
print("  b4 loaded")

f.close()
gc.collect()

mem_after = gc.mem_free()
print(f"[OK]   Model loaded. Memory used: {mem_before - mem_after} bytes")
print(f"[INFO] Free memory: {mem_after} bytes")
